# docker-compose.yml
version: '3.1'

services:
  db:
    image: docker.io/library/postgres
    restart: always
    environment:
      - POSTGRES_USER=passparty
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=passparty
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - 4567:4567
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: passparty
      DATABASE_USER: passparty
      DATABASE_PASSWORD: pass
    depends_on:
      - db